# Site settings

author: Nyasuh
email: nyasuh.dot@gmail.com
twitter_username: R_wahyudi24
github_username:  nyasuhh
googleplus_username: nyasuh
facebook_username: rochmanwah
instagram_username:  nyasuh
disqus_username: nyasuh
tumblr_username : zoldyck-dot
title: Nyasuh

baseurl: ""    # the subpath of your site
url: ""

description: "Need more coffee"

favo: "Whoami ?"
descrpt: "Do you know me ?"

#
# Build settings
#

markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "superscript"]

highlighter: pygments

sass:
    style: compressed

permalink: /posts/:categories/:title.html

paginate: 4
#paginate_path: 'page/:num'

gems: [jekyll-paginate]


# commentted option
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt
